project:
  type: website

website:
  title: "quarto-a11y-test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - style.scss
    toc: true
    highlight-style: a11y



